### ISSUE TITLE
Multiple linked containers with One Hidden Service

### ISSUE THREAD

**Issue by Abhinav-Biswas** [cmehay/docker-tor-hidden-service#13]
Is it possible to host multiple linked containers (for eg. one container running web server with exposed port 80 and another container running ssh with exposed port 22) as a single tor hidden service with single .onion address?

**Comment by cmehay** [comment]
It's not possible right now.

Some internal structures need to be rewritten.

**Comment by Abhinav-Biswas** [comment]
Can you explain those internal structures in short?

**Comment by cmehay** [comment]
This is the way how the services are serialized to generate configuration, I'm working on a better way to do that.
