### ISSUE TITLE
--link deprecated

### ISSUE THREAD

**Issue by tgeek77** [cmehay/docker-tor-hidden-service#18]
According to the current Docker documentation, the --link flag is deprecated and will eventually be removed. Will you container still work without that?

Warning: The --link flag is a deprecated legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

**Comment by cmehay** [comment]
Yes, the container can work without --link environment variable. You can take a look to the `docker-compose.v2.yml` file to see how to link tor container with services using docker networks.
