### ISSUE TITLE
Support for onion v3

### ISSUE THREAD

**Issue by cmehay** [cmehay/docker-tor-hidden-service#20]
Dear me, please add support for onion v3 addresses.

**Comment by venomone** [comment]
Yes please!

**Comment by cmehay** [comment]
Update is on the way, I just created a python lib to manage hidden services keys. It will be soon added to this project. 

Implementing Tor Ed25519 for onion v3 addresses was not easy as Tor don't keep private keys as regular 32 bytes random data but the hashed key which leads to incompatibility with crypto library binding.

https://github.com/cmehay/pytor
