### ISSUE TITLE
Latest image broken

### ISSUE THREAD

**Issue by s1dney** [cmehay/docker-tor-hidden-service#30]
hello

missprint in docker-compose.v2.yml and README.MD:
HELLO_TOR_SERVIV(!)E_KEY
i suspect because of this v2 tor keys just not tested and do not work correctly
right now if i fix typo:
```
Entrypoint #033[33mWARNING #033[0m File "/usr/lib/python3.6/site-packages/pycryptodome-3.8.1-py3.6-linux-x86_64.egg/Crypto/PublicKey/RSA.py", line 754, in import_key#033[0m
Entrypoint #033[33mWARNING #033[0m     raise ValueError("RSA key format is not supported")#033[0m
```
otherwise new key will be created

**Comment by cmehay** [comment]
I'm sorry, I do not understand your issue.

I do not see any typo in docker-compose.v2.yml and README.MD files.

The keys in files are here just for example and not attempted to be used in production.

```
 TOR_VERSION='0.4.0.5' docker-compose -f docker-compose.v2.yml up --force-recreate
Recreating docker-tor-hidden-service_again_1 ... done
Recreating docker-tor-hidden-service_hello_1 ... done
Recreating docker-tor-hidden-service_world_1 ... done
Recreating docker-tor-hidden-service_tor_1   ... done
Attaching to docker-tor-hidden-service_world_1, docker-tor-hidden-service_again_1, docker-tor-hidden-service_hello_1, docker-tor-hidden-service_tor_1
tor_1    | Entrypoint INFO     foo: xwjtp3mj427zdp4tljiiivg2l5ijfvmt5lcsfaygtpp6cw254kykvpyd.onion:88, xwjtp3mj427zdp4tljiiivg2l5ijfvmt5lcsfaygtpp6cw254kykvpyd.onion:8000
tor_1    | Entrypoint INFO     hello: 5azvyr7dvvr4cldn.onion:80, 5azvyr7dvvr4cldn.onion:800, 5azvyr7dvvr4cldn.onion:8888
```

**Comment by s1dney** [comment]
HELLO_TOR_SERVIVE_KEY
SERVIVE not SERVICE

**Comment by cmehay** [comment]
Oh you're right, sorry.

But after fixing the typo, do not reproduce your issue with the v2 private key.

The test for v2 `*_TOR_SERVIVE_KEY` is missing, I will add one.

**Comment by cmehay** [comment]
Please tell me if the problem is solved, tests have been added and I can't reproduce the issue.
