### ISSUE TITLE
multiple port mapping

### ISSUE THREAD

**Issue by fflo** [cmehay/docker-tor-hidden-service#8]
Hi Christophe,

is it possible to map multiple ports to a linked container?
like i.e: onion:80 -> linked_container:8080 and onion:88 -> linked_container:8088

**Comment by cmehay** [comment]
It's not possible right now.

But it should not be hard to add this.

**Comment by fflo** [comment]
That would be perfect. Thank you 👍

**Comment by fflo** [comment]
Thank you. It's working fine.
