### ISSUE TITLE
Add ssl support

### ISSUE THREAD

**Issue by freqmand** [cmehay/docker-tor-hidden-service#81]
I know that adding `https` to onion website doesn't make a lot of sense, but it will be a good option to add it, some users scare when they see `http` 
example of onion websites that use https : 
https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion
https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion

is it possible to add ssl support to the project? or can someone describe a way to add it ? 

thanks

**Comment by cmehay** [comment]
I don't really know how it is possible to certificate a onion domain, but unless this is integrated inside `tor` itself, I don't know how it could be added in this project without creating a third party tool.
