### ISSUE TITLE
Some private keys are not working

### ISSUE THREAD

**Issue by Leichesters** [cmehay/docker-tor-hidden-service#93]
I used `mkp224o` (https://github.com/cathugger/mkp224o) to generate v3 private keys but some of them do not work.

I first created the keys and then base64 them using `cat hs_ed25519_secret_key | base64 > out.txt && cat out.txt`.

Working example (I'm not going to use these keys no worries):
```
Address: testms76ahnlffcq7jzmrfu34y6adnh3rydnwd4ugmbqlm6uo5xmiaad.onion
Private key:
PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAAC4hjCHAKudqdFXoJfpyjZ0EsrAs2yUjYfB
Q6QJMgINYzX8l7c5ScogTmYkVfeHlbi2FwhnOAkRtGaoa0juee9W
```

Failing example:
```
Address: testimanfqjl6ehujvl4ptau35ykujdccxhndy73bvztbzp6f52rdjad.onion
Private key:
PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAAAACZk2fTFszTrb+L0afrmDf4WHwBoEbeQi
37A4PX8lUykL1JWDUyMv8VnNa+g9499q0o7QRcaxmm06joY9N0Q2
```

The failing example shows this error

```
Exception: Private key does not seems to be a valid ed25519 tor key
```

**Comment by cmehay** [comment]
Sorry but I can't reproduce, the private key you provided in the failing example is working when passing it in the env or by file in secrets.

Are you sure you didn't make a mistake when handling the keys?

**Comment by Leichesters** [comment]
Strangely the key works for me now too. Guess my pc just had a bad day :shrug:
